name: Caller

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "A number input"
        required: false
        type: number

jobs:
  caller1:
    uses: ./.github/workflows/callee.yml
    with:
      input1: 12

  caller2:
    uses: ./.github/workflows/callee.yml
    with:
      input1: ${{ fromJSON(inputs.input1) }}
